# Generated by Django 5.0.2 on 2024-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_cities_id_dept_remove_persons_id_exp_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='birthdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
